[package]

	name = "aoc-search"
	version = "0.1.0"
	edition = "2021"

[lib]

	crate-type = [ "rlib", "dylib" ]
	path = "search.rs"

[dependencies]

	aoc-grid = { path = "../grid" }
	aoc-misc = { path = "../misc" }
