#!/bin/bash

export CARGO_TERM_COLOR="always"

declare year="$(basename $PWD)"

function main {
	local mode
	local package
	local profile
	local -a run_args
	while [[ "$#" != 0 ]]; do
		local arg="$1"; shift
		case "$arg" in
			(day-*) package="aoc-$year-day-${arg:4}" ;;
			(dev|release|release-lto) profile="$arg" ;;
			(flamegraph|run|run-test|test) mode="$arg" ;;
			(part-1|part-2) run_args+=( "$arg" ) ;;
			(--width) flamegraph_width="$1"; shift ;;
			(--)
				case "$mode" in
					(""|run|run-test|flamegraph) run_args+=( "$@" ) ;;
					(test) test_args+=( "$@" ) ;;
				esac
				shift $#
				;;
			(*)
				echo "Unknown command: $arg"
				exit 1
				;;
		esac
	done
	local -a cargo_args
	if [[ -z "$mode" ]]; then mode="run-test"; fi
	if [[ -z "$profile" && "$mode" = "flamegraph" ]]; then profile="flamegraph"; fi
	if [[ -n "$package" ]]; then cargo_args+=( --package "$package" ); fi
	if [[ -n "$profile" ]]; then cargo_args+=( --profile "$profile" ); fi
	case "$mode" in
		(run-test)
			cargo run "${cargo_args[@]}" -- "${run_args[@]}"
			cargo test "${cargo_args[@]}" -- "${test_args[@]}"
			;;
		(run)
			cargo run "${cargo_args[@]}" -- "${run_args[@]}"
			;;
		(test)
			cargo test "${cargo_args[@]}" -- "${test_args[@]}"
			;;
		(flamegraph)
			cargo_args+=( --image-width "${flamegraph_width:-4000}" )
			cargo_args+=( --palette "rust" )
			cargo flamegraph "${cargo_args[@]}" -- "${run_args[@]}" \
				&& (eog flamegraph.svg &)
			;;
	esac
}

main "$@"
