#!/bin/bash

export CARGO_TERM_COLOR="always"

declare year="$(basename $PWD)"

function main {
	local mode
	local package
	local profile
	local -a run_args
	while [[ "$#" != 0 ]]; do
		local arg="$1"; shift
		case "$arg" in
			(day-*) package="aoc-$year-day-${arg:4}" ;;
			(dev|release|release-lto) profile="$arg" ;;
			(clippy|flamegraph|run|run-test|test) mode="$arg" ;;
			(part-1|part-2) run_args+=( "$arg" ) ;;
			(--width) flamegraph_width="$1"; shift ;;
			(--)
				case "$mode" in
					(""|run|run-test|flamegraph) run_args+=( "$@" ) ;;
					(test) test_args+=( "$@" ) ;;
				esac
				shift $#
				;;
			(*)
				echo "Unknown command: $arg"
				exit 1
				;;
		esac
	done
	local -a cargo_args
	if [[ -z "$mode" ]]; then mode="run-test"; fi
	if [[ -z "$profile" && "$mode" = "flamegraph" ]]; then profile="flamegraph"; fi
	if [[ -n "$package" ]]; then cargo_args+=( --package "$package" ); fi
	if [[ -n "$profile" ]]; then cargo_args+=( --profile "$profile" ); fi
	case "$mode" in
		(clippy)
			local -a clippy_args
			clippy_args+=( --allow "clippy::needless_collect" )
			clippy_args+=( --allow "clippy::needless_range_loop" )
			clippy_args+=( --allow "clippy::new_without_default" )
			clippy_args+=( --allow "clippy::print_with_newline" )
			clippy_args+=( --allow "clippy::useless_format" )
			clippy_args+=( --allow "clippy::vec_init_then_push" )
			clippy_args+=( --allow "clippy::write_with_newline" )
			cargo clippy "${cargo_args[@]}" -- "${clippy_args[@]}"
			;;
		(run-test)
			time env time -v cargo run "${cargo_args[@]}" -- "${run_args[@]}"
			time env time -v cargo test "${cargo_args[@]}" -- "${test_args[@]}"
			;;
		(run)
			time env time -v cargo run "${cargo_args[@]}" -- "${run_args[@]}"
			;;
		(test)
			time env time -v cargo test "${cargo_args[@]}" -- "${test_args[@]}"
			;;
		(flamegraph)
			cargo_args+=( --image-width "${flamegraph_width:-4000}" )
			cargo_args+=( --palette "rust" )
			local timestamp=$(date +"%Y-%m-%d-%H:%M:%S")
			if cargo flamegraph \
				"${cargo_args[@]}" \
				--output target/flamegraph-$timestamp.svg \
				-- \
				"${run_args[@]}"
			then
				(eog flamegraph.svg target/flamegraph-$timestamp.svg &)
				mv perf.data target/flamegraph-$timestamp.perf-data
				ln -fns flamegraph-$timestamp.svg target/flamegraph-latest.svg
				ln -fns flamegraph-$timestamp.perf-data target/flamegraph-latest.perf-data
			fi
			;;
	esac
}

main "$@"
