#!/bin/bash

declare -a cpus
declare -a years=( {2015..2021} )
declare default_fuzz_time=15
declare default_shrink_time=5

case "$HOSTNAME" in
	("mufasa") cpus=( {8..15} ) ;;
	("simba") cpus=( {8..15} ) ;;
	(*) echo "Hostname not recognised" >&2; exit 1 ;;
esac

function dispatch {
	local command="${1:-fuzz}"; shift
	case "$command" in
		(fuzz|minimise|shrink) launch "$command" "$@" ;;
		(worker) worker "$@" ;;
		(*) echo "Syntax error" >&2; exit 1 ;;
	esac
}

function launch {

	local mode="$1"

	# basic setup

	declare main_pid="$$"
	declare work_dir="/run/user/$UID/aoc-fuzz-script-$main_pid"
	mkdir -p "$work_dir"
	trap "rm -rf $work_dir" EXIT

	# create fifos to communicate with workers

	for cpu in "${cpus[@]}"; do
		mkfifo "$work_dir/$cpu-produce"
		mkfifo "$work_dir/$cpu-consume"
	done

	# start controller

	coproc control { controller "$mode"; }

	# run workers in screen

	screenrc="$work_dir/screen-rc"
	{
		echo "startup_message off"
		echo "caption always \"%{= kw} %t %-=\""
		for cpu in "${cpus[@]}"; do
			if [[ $cpu != "${cpus[0]}" ]]; then
				echo "split"
				echo "focus"
			fi
			cpu_mask=$(printf "0x%x" $((1 << cpu)))
			echo "screen taskset $cpu_mask nice misc/fuzz-script worker $main_pid $cpu"
		done
	} > $screenrc

	exec screen -c $screenrc -e ^@@

}

function iterator {
	local mode="$1"
	local repeat="$2"
	local targets=$(
		for year in "${years[@]}"; do
			for day in {01..25}; do
				if [[ ! -f "fuzz/src/$year-day-$day.rs" ]]; then continue; fi
				echo $year-day-$day
			done
		done | shuf
	)
	if "$repeat"; then
		while true; do
			for target in $targets; do
				echo "$mode $target"
			done
		done
	else
		for target in $targets; do
			echo "$mode $target"
		done
		while true; do
			echo "done"
		done
	fi
}

function controller {

	local mode="$1"
	local -A produce_fds
	local -A consume_fds

	# open fifos to talk to workers

	for cpu in "${cpus[@]}"; do
		exec {produce_fd}>"$work_dir/$cpu-produce"
		produce_fds[$cpu]=$produce_fd
		exec {consume_fd}<"$work_dir/$cpu-consume"
		consume_fds[$cpu]=$consume_fd
	done

	# iterate targets

	coproc iterate {
		case "$mode" in
			(fuzz) iterator "$mode" true ;;
			(minimise) iterator "$mode" false ;;
			(shrink) iterator "$mode" true ;;
		esac
	}

	# feed tasks to workers when requested

	while true; do
		while true; do
			for cpu in "${cpus[@]}"; do
				produce_fd="${produce_fds[$cpu]}"
				consume_fd="${consume_fds[$cpu]}"
				if ! read -t 0 -u "$consume_fd"; then continue; fi
				read -u "$consume_fd"
				read -u "${iterate[0]}"
				echo "$REPLY" >&$produce_fd
			done
			sleep 0.4
		done
	done

}

function worker {

	# basic setup

	declare main_pid="$1"
	declare cpu="$2"
	declare work_dir="/run/user/$UID/aoc-fuzz-script-$main_pid"
	declare title_prefix="[cpu $cpu]"

	# exit entire screen session on interrupt

	trap "screen -X quit" INT

	# open fifos to communicate with controller

	exec 3<"$work_dir/$cpu-produce"
	exec 4>"$work_dir/$cpu-consume"

	( while true; do

		# get task from controller

		screen -X title "$title_prefix looking for work"
		echo "ready" >&4
		local -a input
		read -u 3 -a input
		local mode="${input[0]}"
		if [[ "$mode" == "done" ]]; then exit 0; fi
		local target="${input[1]}"
		local year="${target%-day-*}"
		local day="${target#*-day-}"

		# execute task

		case "$mode" in

			(fuzz)
				screen -X title "$title_prefix $year/day-$day fuzzing"
				misc/build-script fuzz year-$year day-$day \
					-- \
					-- -max_total_time=$((default_fuzz_time * 60))
				;;

			(shrink)
				screen -X title "$title_prefix $year/day-$day shrinking"
				misc/build-script fuzz year-$year day-$day \
					-- \
					-- -max_total_time=$((default_shrink_time * 60)) -shrink=1
				;;

			(minimise)
				screen -X title "$title_prefix $year/day-$day minimising"
				misc/build-script fuzz year-$year day-$day cmin
				;;

		esac

	done ) |& {

		# supress blank line at end of output

		while true; do
			if ! read; then break; fi
			printf "\n%s" "$REPLY"
		done

	}

}

dispatch "$@"
