[package]

	name = "aoc-2019-day-08"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	edition = "2021"
	description = "Advent of Code 2019: Day 8: Space Image Format"
	repository = "https://github.com/jamespharaoh/advent-of-code/tree/master/2019/day-08"
	license = "MIT"
	publish = false

[dependencies]

	aoc-common = { path = "../../common" }
	aoc-ocr = { path = "../../common/ocr" }

[build-dependencies]

	aoc-codegen = { path = "../../misc/codegen" }

[lib]

	path = "lib.rs"
	doctest = false
	crate-type = [ "rlib", "dylib" ]

[[bin]]

	name = "aoc-2019-day-08"
	path = "main.rs"
	test = false
	doctest = false
	bench = false
