[package]

	name = "aoc-2021-day-19"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	edition = "2021"
	description = "Advent of Code 2021: Day 19: Beacon Scanner"
	repository = "https://github.com/jamespharaoh/advent-of-code/tree/master/2021/day-19"
	license = "MIT"
	publish = false

[dependencies]

	aoc-bithash = { path = "../../common/bithash" }
	aoc-common = { path = "../../common" }
	aoc-pos = { path = "../../common/pos" }

[build-dependencies]

	aoc-codegen = { path = "../../misc/codegen" }

[lib]

	crate-type = [ "rlib", "dylib" ]

[[bin]]

	name = "aoc-2021-day-19"
	test = false
	bench = false
