[package]

	name = "aoc-2017-knot"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	edition = "2021"
	description = "Advent of Code 2017: Knot Hash"
	repository = "https://github.com/jamespharaoh/advent-of-code/tree/master/2017/knot"
	license = "MIT"
	publish = false

[dependencies]

	aoc-common = { path = "../../common" }

[lib]

	path = "knot.rs"
	crate-type = [ "rlib", "dylib" ]
