[package]

	name = "aoc-2021-day-22"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	edition = "2021"
	description = "Advent of Code 2021: Day 22: Reactor Reboot"
	repository = "https://github.com/jamespharaoh/advent-of-code/tree/master/2021/day-22"
	license = "MIT"
	publish = false

[dependencies]

	aoc-common = { path = "../../common" }
