[package]

	name = "aoc-parser"
	version = "0.1.0"
	edition = "2021"

[lib]

	crate-type = [ "rlib", "dylib" ]
	path = "parser.rs"

[dependencies]

	aoc-inpstr = { path = "../inpstr" }
	aoc-misc = { path = "../misc" }
	aoc-nums = { path = "../nums" }
