version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/common"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/2015"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/2021"
    schedule:
      interval: "weekly"
