(function() {var implementors = {
"aoc_2015_day_04":[["impl <a class=\"trait\" href=\"clap/derive/trait.Args.html\" title=\"trait clap::derive::Args\">Args</a> for <a class=\"struct\" href=\"aoc_2015_day_04/cli/struct.RunArgs.html\" title=\"struct aoc_2015_day_04::cli::RunArgs\">RunArgs</a>"],["impl <a class=\"trait\" href=\"clap/derive/trait.Args.html\" title=\"trait clap::derive::Args\">Args</a> for <a class=\"struct\" href=\"aoc_2015_day_04/cli/struct.FindTestCaseArgs.html\" title=\"struct aoc_2015_day_04::cli::FindTestCaseArgs\">FindTestCaseArgs</a>"]],
"aoc_2018_day_21":[["impl <a class=\"trait\" href=\"clap/derive/trait.Args.html\" title=\"trait clap::derive::Args\">Args</a> for <a class=\"struct\" href=\"aoc_2018_day_21/analyser/struct.Args.html\" title=\"struct aoc_2018_day_21::analyser::Args\">Args</a>"]],
"aoc_2019_day_13":[["impl <a class=\"trait\" href=\"clap/derive/trait.Args.html\" title=\"trait clap::derive::Args\">Args</a> for <a class=\"struct\" href=\"aoc_2019_day_13/run/struct.RunArgs.html\" title=\"struct aoc_2019_day_13::run::RunArgs\">RunArgs</a>"]],
"aoc_2019_day_25":[["impl <a class=\"trait\" href=\"clap/derive/trait.Args.html\" title=\"trait clap::derive::Args\">Args</a> for <a class=\"struct\" href=\"aoc_2019_day_25/run/struct.RunArgs.html\" title=\"struct aoc_2019_day_25::run::RunArgs\">RunArgs</a>"]],
"aoc_2021_day_13":[["impl <a class=\"trait\" href=\"clap/derive/trait.Args.html\" title=\"trait clap::derive::Args\">Args</a> for <a class=\"struct\" href=\"aoc_2021_day_13/tool/struct.RunArgs.html\" title=\"struct aoc_2021_day_13::tool::RunArgs\">RunArgs</a>"]],
"aoc_2021_day_20":[["impl <a class=\"trait\" href=\"clap/derive/trait.Args.html\" title=\"trait clap::derive::Args\">Args</a> for <a class=\"struct\" href=\"aoc_2021_day_20/tool/struct.RunArgs.html\" title=\"struct aoc_2021_day_20::tool::RunArgs\">RunArgs</a>"]],
"aoc_2021_day_23":[["impl <a class=\"trait\" href=\"clap/derive/trait.Args.html\" title=\"trait clap::derive::Args\">Args</a> for <a class=\"struct\" href=\"aoc_2021_day_23/tools/struct.RunArgs.html\" title=\"struct aoc_2021_day_23::tools::RunArgs\">RunArgs</a>"],["impl <a class=\"trait\" href=\"clap/derive/trait.Args.html\" title=\"trait clap::derive::Args\">Args</a> for <a class=\"struct\" href=\"aoc_2021_day_23/tools/struct.InternalsArgs.html\" title=\"struct aoc_2021_day_23::tools::InternalsArgs\">InternalsArgs</a>"]],
"aoc_2021_day_24":[["impl <a class=\"trait\" href=\"clap/derive/trait.Args.html\" title=\"trait clap::derive::Args\">Args</a> for <a class=\"struct\" href=\"aoc_2021_day_24/tool/struct.AllArgs.html\" title=\"struct aoc_2021_day_24::tool::AllArgs\">AllArgs</a>"],["impl <a class=\"trait\" href=\"clap/derive/trait.Args.html\" title=\"trait clap::derive::Args\">Args</a> for <a class=\"struct\" href=\"aoc_2021_day_24/tool/struct.MachineArgs.html\" title=\"struct aoc_2021_day_24::tool::MachineArgs\">MachineArgs</a>"],["impl <a class=\"trait\" href=\"clap/derive/trait.Args.html\" title=\"trait clap::derive::Args\">Args</a> for <a class=\"struct\" href=\"aoc_2021_day_24/tool/struct.SolverArgs.html\" title=\"struct aoc_2021_day_24::tool::SolverArgs\">SolverArgs</a>"]],
"clap":[]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()