[package]

	name = "aoc2018"
	version = "0.1.0"
	edition = "2021"

[dependencies]

	chrono = "0.4"
	itertools = "0.10"
	parse-display = "0.5"
	parse-display-derive = { path = "parse-display/parse-display-derive" }
	regex = "1.6"
	text_io = "0.1"
