[package]

	name = "aoc2018"
	version = "0.1.0"
	edition = "2021"

[dependencies]

	chrono = "*"
	itertools = "*"
	parse-display = "*"
	parse-display-derive = { path = "../../rust/parse-display/parse-display-derive" }
	regex = "*"
	text_io = "*"
