[package]

	name = "aoc-2016-cpu"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	edition = "2021"
	description = "Advent of Code 2016: Prototype CPU"
	repository = "https://github.com/jamespharaoh/advent-of-code/tree/master/2016/cpu"
	license = "MIT"
	publish = false

[dependencies]

	aoc-common = { path = "../../common" }

[lib]

	path = "lib.rs"
	crate-type = [ "rlib", "dylib" ]
