[package]

	name = "aoc-puzzle"
	version = "0.1.0"
	edition = "2021"

[dependencies]

	aoc-args = { path = "../args" }
	aoc-misc = { path = "../misc" }
	aoc-nums = { path = "../nums" }

[lib]

	path = "lib.rs"
	crate-type = [ "rlib", "dylib" ]
