[package]

	name = "aoc-2019-intcode"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	edition = "2021"
	description = "Advent of Code 2019: Intcode"
	repository = "https://github.com/jamespharaoh/advent-of-code/tree/master/2019/intcode"
	license = "MIT"
	publish = false

[dependencies]

	aoc-common = { path = "../../common" }

[lib]

	path = "intcode.rs"
	crate-type = [ "rlib", "dylib" ]
