[package]

	name = "aoc-ocr"
	version = "0.1.0"
	edition = "2021"

[lib]

	crate-type = [ "rlib", "dylib" ]
	path = "lib.rs"

[dependencies]

	aoc-misc = { path = "../misc" }
	aoc-nums = { path = "../nums" }

[lints.rust]

	unexpected_cfgs = { level = "warn", check-cfg = [ "cfg (fuzzing)" ] }
