[package]

	name = "aoc-2016-day-19"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	edition = "2021"
	description = "Advent of Code 2016: Day 19: An Elephant Named Joseph"
	repository = "https://github.com/jamespharaoh/advent-of-code/tree/master/2016/day-19"
	license = "MIT"
	publish = false

[dependencies]

	aoc-common = { path = "../../common" }

[lib]

	doctest = false
	crate-type = [ "rlib", "dylib" ]

[build-dependencies]

	aoc-codegen = { path = "../../misc/codegen" }

[[bin]]

	name = "aoc-2016-day-19"
	test = false
	doctest = false
	bench = false
