(function() {var implementors = {
"aoc_2017_cpu":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"aoc_2017_cpu/enum.CpuError.html\" title=\"enum aoc_2017_cpu::CpuError\">CpuError</a>"]],
"aoc_2018_cpu":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"aoc_2018_cpu/enum.CpuError.html\" title=\"enum aoc_2018_cpu::CpuError\">CpuError</a>"]],
"aoc_2019_intcode":[["impl&lt;Val: <a class=\"trait\" href=\"aoc_nums/int/trait.Int.html\" title=\"trait aoc_nums::int::Int\">Int</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"aoc_2019_intcode/enum.RunResult.html\" title=\"enum aoc_2019_intcode::RunResult\">RunResult</a>&lt;Val&gt;"]],
"aoc_2021_day_18":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"aoc_2021_day_18/model/enum.ParseError.html\" title=\"enum aoc_2021_day_18::model::ParseError\">ParseError</a>"]],
"aoc_args":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"aoc_args/enum.ArgsParseError.html\" title=\"enum aoc_args::ArgsParseError\">ArgsParseError</a>"]],
"aoc_misc":[],
"aoc_nums":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"aoc_nums/struct.Overflow.html\" title=\"struct aoc_nums::Overflow\">Overflow</a>"]],
"aoc_parser":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"aoc_parser/enum.ParseError.html\" title=\"enum aoc_parser::ParseError\">ParseError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()