[package]

	name = "aoc-pos"
	version = "0.1.0"
	edition = "2021"

[lib]

	crate-type = [ "rlib", "dylib" ]
	path = "pos.rs"

[dependencies]

	aoc-misc = { path = "../misc" }
	aoc-nums = { path = "../nums" }
