[package]

	name = "aoc-2015-fuzz"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	publish = false
	edition = "2018"

[package.metadata]

	cargo-fuzz = true

[dependencies]

	libfuzzer-sys = "0.4"

	aoc-2015 = { path = ".." }

[workspace]

	members = [ "." ]

[[bin]]

	name = "day-01"
	path = "src/day-01.rs"
	test = false
	doc = false

[[bin]]

	name = "day-02"
	path = "src/day-02.rs"
	test = false
	doc = false

[[bin]]

	name = "day-03"
	path = "src/day-03.rs"
	test = false
	doc = false

[[bin]]

	name = "day-04"
	path = "src/day-04.rs"
	test = false
	doc = false

[[bin]]

	name = "day-05"
	path = "src/day-05.rs"
	test = false
	doc = false

[[bin]]

	name = "day-06"
	path = "src/day-06.rs"
	test = false
	doc = false

[[bin]]

	name = "day-07"
	path = "src/day-07.rs"
	test = false
	doc = false

[[bin]]

	name = "day-08"
	path = "src/day-08.rs"
	test = false
	doc = false

# TODO 09 to 16

[[bin]]

	name = "day-17"
	path = "src/day-17.rs"
	test = false
	doc = false
