[package]

	name = "aoc-2015-fuzz"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	publish = false
	edition = "2018"

[package.metadata]

	cargo-fuzz = true

[dependencies]

	libfuzzer-sys = "0.4"

	aoc-2015 = { path = ".." }

[workspace]

	members = [ "." ]

[[bin]]

	name = "day-01"
	path = "src/day-01.rs"
	test = false
	doc = false

[[bin]]

	name = "day-02"
	path = "src/day-02.rs"
	test = false
	doc = false

[[bin]]

	name = "day-03"
	path = "src/day-03.rs"
	test = false
	doc = false

[[bin]]

	name = "day-04"
	path = "src/day-04.rs"
	test = false
	doc = false

[[bin]]

	name = "day-05"
	path = "src/day-05.rs"
	test = false
	doc = false

[[bin]]

	name = "day-06"
	path = "src/day-06.rs"
	test = false
	doc = false

[[bin]]

	name = "day-07"
	path = "src/day-07.rs"
	test = false
	doc = false

[[bin]]

	name = "day-08"
	path = "src/day-08.rs"
	test = false
	doc = false

[[bin]]

	name = "day-09"
	path = "src/day-09.rs"
	test = false
	doc = false

[[bin]]

	name = "day-10"
	path = "src/day-10.rs"
	test = false
	doc = false

[[bin]]

	name = "day-11"
	path = "src/day-11.rs"
	test = false
	doc = false

[[bin]]

	name = "day-12"
	path = "src/day-12.rs"
	test = false
	doc = false

[[bin]]

	name = "day-13"
	path = "src/day-13.rs"
	test = false
	doc = false

[[bin]]

	name = "day-14"
	path = "src/day-14.rs"
	test = false
	doc = false

[[bin]]

	name = "day-15"
	path = "src/day-15.rs"
	test = false
	doc = false

[[bin]]

	name = "day-16"
	path = "src/day-16.rs"
	test = false
	doc = false

[[bin]]

	name = "day-17"
	path = "src/day-17.rs"
	test = false
	doc = false

[[bin]]

	name = "day-18"
	path = "src/day-18.rs"
	test = false
	doc = false

[[bin]]

	name = "day-19"
	path = "src/day-19.rs"
	test = false
	doc = false

[[bin]]

	name = "day-20"
	path = "src/day-20.rs"
	test = false
	doc = false

[[bin]]

	name = "day-21"
	path = "src/day-21.rs"
	test = false
	doc = false

[[bin]]

	name = "day-22"
	path = "src/day-22.rs"
	test = false
	doc = false

[[bin]]

	name = "day-23"
	path = "src/day-23.rs"
	test = false
	doc = false

[[bin]]

	name = "day-24"
	path = "src/day-24.rs"
	test = false
	doc = false

[[bin]]

	name = "day-25"
	path = "src/day-25.rs"
	test = false
	doc = false
