[package]
name = "aoc-2019-day-18-part-1"
version = "0.1.0"
authors = ["james <james@pharaoh.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
