[package]

	name = "aoc-2016-day-14"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	edition = "2021"
	description = "Advent of Code 2016: Day 14: One-Time Pad"
	repository = "https://github.com/jamespharaoh/advent-of-code/tree/master/2016/day-14"
	license = "MIT"
	publish = false

[dependencies]

	aoc-common = { path = "../../common" }
	aoc-md5 = { path = "../../common/md5" }
	aoc-parallel = { path = "../../common/parallel" }

[build-dependencies]

	aoc-codegen = { path = "../../misc/codegen" }

[lib]

	path = "lib.rs"
	doctest = false
	crate-type = [ "rlib", "dylib" ]

[[bin]]

	name = "aoc-2016-day-14"
	path = "main.rs"
	test = false
	doctest = false
	bench = false
