[package]

	name = "aoc-2021-day-06"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	edition = "2021"
	description = "Advent of Code 2021: Day 6: Lanternfish"
	repository = "https://github.com/jamespharaoh/advent-of-code/tree/master/2021/day-06"
	license = "MIT"
	publish = false

[dependencies]

	aoc-common = { path = "../../common" }

[build-dependencies]

	aoc-codegen = { path = "../../misc/codegen" }

[lib]

	crate-type = [ "rlib", "dylib" ]

[[bin]]

	name="aoc-2021-day-06"
	test = false
	bench = false
