[package]

	name = "aoc-2018-day-16"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	edition = "2021"
	description = "Advent of Code 2018: Day 16: Chronal Classification"
	repository = "https://github.com/jamespharaoh/advent-of-code/tree/master/2018/day-16"
	license = "MIT"
	publish = false

[dependencies]

	aoc-2018-cpu = { path = "../cpu" }
	aoc-common = { path = "../../common" }

[build-dependencies]

	aoc-codegen = { path = "../../misc/codegen" }

[lib]

	path = "lib.rs"
	doctest = false
	crate-type = [ "rlib", "dylib" ]

[[bin]]

	name = "aoc-2018-day-16"
	path = "main.rs"
	test = false
	doctest = false
	bench = false
