[package]

	name = "aoc-misc"
	version = "0.1.0"
	edition = "2021"

[lib]

	crate-type = [ "rlib", "dylib" ]
	path = "misc.rs"

[dependencies]

	ahash = { version = "*", features = [ "std" ] }

[lints.rust]

	unexpected_cfgs = { level = "warn", check-cfg = [ "cfg (fuzzing)" ] }
