[package]

	name = "aoc-2021-day-15"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	edition = "2021"
	description = "Advent of Code 2021: Day 15: Chiton"
	repository = "https://github.com/jamespharaoh/advent-of-code/tree/master/2021/day-15"
	license = "MIT"
	publish = false

[dependencies]

	aoc-common = { path = "../../common" }
	aoc-grid = { path = "../../common/grid" }
	aoc-pos = { path = "../../common/pos" }
	aoc-search = { path = "../../common/search" }

[build-dependencies]

	aoc-codegen = { path = "../../misc/codegen" }

[lib]

	doctest = false
	crate-type = [ "rlib", "dylib" ]

[[bin]]

	name = "aoc-2021-day-15"
	test = false
	doctest = false
	bench = false
