[package]

	name = "aoc-common"
	version = "0.1.0"
	edition = "2021"

[dependencies]

	arrayvec = "*"
	clap = { version = "*", features = [ "derive" ] }
	itertools = "*"

[lib]

	crate-type = [ "rlib", "dylib" ]
