[package]

	name = "aoc-2021-day-14"
	version = "0.1.0"
	authors = [ "James Pharaoh <james@pharaoh.uk>" ]
	edition = "2021"
	description = "Advent of Code 2021: Day 14: Extended Polymerization"
	repository = "https://github.com/jamespharaoh/advent-of-code/tree/master/2021/day-14"
	license = "MIT"
	publish = false

[dependencies]

	aoc-common = { path = "../../common" }

[build-dependencies]

	aoc-codegen = { path = "../../misc/codegen" }

[lib]

	doctest = false
	crate-type = [ "rlib", "dylib" ]

[[bin]]

	name = "aoc-2021-day-14"
	test = false
	doctest = false
	bench = false
