name: rust

on:

  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  schedule:
    - cron: "33 3 * * *"

env:

  CARGO_TERM_COLOR: always

jobs:

  clippy:
    runs-on: ubuntu-latest
    steps:

      - name: Install rust nightly
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          profile: minimal
          toolchain: nightly

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: >
            --all-features
            --
            --deny warnings
            --allow clippy::needless_collect
            --allow clippy::needless_range_loop
            --allow clippy::new_without_default
            --allow clippy::print_with_newline
            --allow clippy::type_complexity
            --allow clippy::useless_format
            --allow clippy::vec_init_then_push
            --allow clippy::write_with_newline

  stable:
    runs-on: ubuntu-latest
    steps:

      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --release

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --release

  beta:
    runs-on: ubuntu-latest
    steps:

      - name: Install rust beta
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: beta

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --release

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --release

  nightly:
    runs-on: ubuntu-latest
    steps:

      - name: Install rust nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --release

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --release
