[package]

	name = "aoc-2018-day-4-part-1"
	version = "0.1.0"
	edition = "2018"

[dependencies]

	chrono = "*"
	itertools = "*"
	parse-display = "*"
	parse-display-derive = "*"
	syn = { features = ["full", "visit"] }
